# Generated by Django 3.2.23 on 2024-01-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snipit',
            field=models.CharField(default='Click Link Above To Read Blog Post...', max_length=200),
        ),
    ]
