# Generated by Django 3.2.23 on 2024-01-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_snipit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snipit',
        ),
    ]
